apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: tomcat-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-cd
  template:
    metadata:
      labels:
        app: tomcat-cd
    spec:
      containers:
      - name: tomcat-cd
        image: vikas1305/java-web-app-cicd:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---        
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: tomcat-cd 
  type: NodePort 
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
